UCloud-FE/react-components

.github/CONTRIBUTING.md
.github/PULL_REQUEST_TEMPLATE.md
DEVELOP.md

Docs update
No docs
Add git commit guideline, contributing, pull request template
No
Yes

Docs: add some docs

---

src/components/DatePicker/Range.jsx
src/components/DatePicker/Range.md
src/components/DatePicker/__demo__/range-hideOptions.jsx
src/components/DatePicker/__demo__/range.jsx
src/components/DatePicker/__test__/__snapshots__/demo.test.js.snap

feature
#3 
Add hideOptions to range for hide the Select in Range
No
*   [x] Follow our contributing docs

feat(DatePicker): add Range.hideOptions

---

src/components/DatePicker/Range.jsx
src/components/DatePicker/Range.md
src/components/DatePicker/__demo__/range-display.jsx
src/components/DatePicker/__test__/__snapshots__/demo.test.js.snap

add display to Range to control display of component
close #8
feature
#8 
Add display to control components in Range
No

feat(DatePicker): add display to Range

---

.circleci/config.yml
.eslintignore
README.md
jest.config.js

test
#16 
Add codecov to CircleCI
No

Test: add Codecov

---

.circleci/config.yml

test
Cache node_modules with package.json
Cache yarn cache and node_modules with yarn.lock
No

CircleCI: add cache of yarn

---

.prettierignore
.prettierrc
.travis.yml

style
Use tabWidth in .editorconfig
Remove tabWidth to use config in .editorconfig
No

style(prettier): remove tabWidth in prettier

---

src/components/DatePicker/DatePicker.jsx
src/components/DatePicker/Month.jsx
src/components/DatePicker/Range.jsx
src/components/DatePicker/style/index.js

feature
no zIndex props
add zIndex
No

DatePicker: add zIndex

---

src/components/Popover/Popover.jsx

feature
No zIndex props
Add zIndex props
No

feat(Popover): add zIndex

---

.circleci/config.yml
jest.config.js
src/components/Popover/Popover.jsx

ci
Collect coverage in TravisCI
Remove coverage collect
No

ci(Travis): remove coverage

---

.eslintrc

chore
globals of global
move test globals to overrides
no

chore(eslint): move eslint globals to overrides

---

src/stores/SimpleStore.js

bug fix
returned ref is not useful
return an object contains unsubscribe handle
No

fix(SimpleStore): fix return ref

---

.circleci/config.yml

ci(Circle): add end job

---

.travis.yml

ci
will trigger build when push to all branch
only trigger build when push to master
no

ci(Travis): donot build push of common branch

---

src/components/Badge/Badge.jsx
src/components/Badge/Badge.md
src/components/Badge/__demo__/customValue.jsx
src/components/Badge/__tests__/__snapshots__/demo.test.js.snap
src/components/Badge/__tests__/index.test.js

test
add customValue demo
add test case
no

test(Badge): add badge test case & demo

---

src/components/Calendar/__tests__/index.test.js

test
add test case of Calendar
No

test(Calendar): add test case

---

src/components/Checkbox/__tests__/index.test.js

test
add test case of checkbox
No

test(Checkbox): add test case

---

src/components/Input/__tests__/index.test.js

test
add test case of Input
No

test(Input): add test case

---

src/stores/__tests__/index.test.js

test
add test case of SimpleStore
No

test(store): add test case of SimpleStore

---

src/utils/__tests__/index.test.js

test
add test case of utils
No

test(utils): add test case of utils

---

src/components/Pagination/Pagination.jsx
src/components/Pagination/__tests__/index.test.js

test(Pagination): add test case & remove unused code

---

.styleguide/components.json
src/components/LocaleProvider/LocaleProvider.jsx
src/components/LocaleProvider/LocaleProvider.md
src/components/LocaleProvider/__demo__/componentlocale.jsx
src/components/LocaleProvider/__demo__/localefile.jsx
src/components/LocaleProvider/__demo__/localeprovider.jsx
src/components/LocaleProvider/__tests__/__snapshots__/demo.test.js.snap
src/components/LocaleProvider/__tests__/demo.test.js
src/components/LocaleProvider/index.jsx
src/components/LocaleProvider/localConsumerDecorator.jsx
src/components/LocaleProvider/locale/en_US.js
src/components/LocaleProvider/locale/zh_CN.js
src/components/Pagination/Pagination.jsx
src/components/Pagination/locale/en_US.js

feature
#41 
add LocaleProvider to manage locale
No

feat(locale): add LocaleProvider to manage locale

---

src/components/DatePicker/DatePicker.jsx
src/components/DatePicker/Month.jsx
src/components/DatePicker/Range.jsx
src/components/DatePicker/__tests__/__snapshots__/demo.test.js.snap
src/components/DatePicker/locale/en_US.js
src/components/DatePicker/locale/zh_CN.js
src/components/LocaleProvider/__demo__/list.jsx
src/components/LocaleProvider/__tests__/__snapshots__/demo.test.js.snap
src/components/LocaleProvider/__tests__/__snapshots__/index.test.js.snap
src/components/LocaleProvider/locale/en_US.js
src/components/LocaleProvider/locale/zh_CN.js

feature
add support of LocaleProvider in DatePicker
use LocaleProvider to control locale in DatePicker
No

feat(DatePicker): add support of LocaleProvider

---

package.json
src/components/LocaleProvider/LocaleProvider.jsx
src/components/LocaleProvider/LocaleProvider.md
src/components/LocaleProvider/__demo__/list.jsx
src/components/LocaleProvider/__tests__/__snapshots__/demo.test.js.snap
src/components/LocaleProvider/__tests__/__snapshots__/index.test.js.snap
src/components/LocaleProvider/__tests__/index.test.js
src/components/LocaleProvider/locale/en_US.js
src/components/LocaleProvider/locale/runtime.js
src/components/LocaleProvider/locale/zh_CN.js
src/components/LocaleProvider/localeConsumerDecorator.jsx
src/components/Modal/Modal.jsx
src/components/Modal/locale/en_US.js
src/components/Modal/locale/zh_CN.js
src/components/Modal/method.jsx

feature
Don't support LocaleProvider
Support LocaleProvider
No
it's special when use method to create Modal. So add runtimeLocale for cache locale.

feat(Modal): add support of LocaleProvider

---

src/components/LocaleProvider/__demo__/list.jsx
src/components/LocaleProvider/__tests__/__snapshots__/demo.test.js.snap
src/components/LocaleProvider/__tests__/__snapshots__/index.test.js.snap
src/components/LocaleProvider/locale/en_US.js
src/components/LocaleProvider/locale/zh_CN.js
src/components/Menu/Menu.jsx
src/components/Menu/SubMenu.jsx
src/components/Menu/locale/en_US.js
src/components/Menu/locale/zh_CN.js

feature
not support LocaleProvider
support LocaleProvider
No

feat(Menu): add support of LocaleProvider

---

src/components/LocaleProvider/__demo__/list.jsx
src/components/LocaleProvider/__tests__/__snapshots__/demo.test.js.snap
src/components/LocaleProvider/__tests__/__snapshots__/index.test.js.snap
src/components/LocaleProvider/locale/en_US.js
src/components/LocaleProvider/locale/zh_CN.js
src/components/Upload/List.jsx
src/components/Upload/Selector.jsx
src/components/Upload/Upload.jsx
src/components/Upload/locale/en_US.js
src/components/Upload/locale/zh_CN.js

feature
not support LocaleProvider
Add support of LocaleProvider
No

feat(Upload): add support of LocaleProvider

---

src/components/Slider/Slider.jsx
src/components/Slider/__tests__/__snapshots__/demo.test.js.snap
src/components/Slider/style/index.js

fix(Slider): fix precision when compute float number

---

src/components/Grid/Col.jsx
src/components/Grid/Col.md
src/components/Grid/__demo__/col-order.jsx
src/components/Grid/__tests__/__snapshots__/demo.test.js.snap
src/components/Pagination/Options.jsx
src/components/Pagination/Pagination.jsx
src/components/Pagination/__tests__/__snapshots__/index.test.js.snap
src/components/Pagination/__tests__/index.test.js
src/components/Popover/__tests__/__snapshots__/index.test.js.snap
src/components/Popover/__tests__/index.test.js
src/components/Switch/__tests__/index.test.js
src/components/Tooltip/__tests__/__snapshots__/index.test.js.snap
src/components/Tooltip/__tests__/index.test.js
src/decorators/__tests__/index.test.js

test(test): fill test cases

---

src/components/NumberInput/__tests__/index.test.js

test(NumberInput): add test case

---

src/components/Slider/Slider.jsx
src/components/Slider/__demo__/marks.jsx
src/components/Slider/__tests__/__snapshots__/demo.test.js.snap
src/components/Slider/__tests__/index.test.js
src/components/Slider/style/index.js
src/components/Tooltip/Tooltip.jsx

feature
No
add ratio to custom mark range width
add step to custom step in diff mark range
No

feat(Slider): add ratio, step to marks

---

src/components/LocaleProvider/__demo__/list.jsx
src/components/LocaleProvider/__tests__/__snapshots__/demo.test.js.snap
src/components/LocaleProvider/__tests__/__snapshots__/index.test.js.snap
src/components/LocaleProvider/__tests__/index.test.js
src/components/LocaleProvider/locale/en_US.js
src/components/LocaleProvider/locale/zh_CN.js
src/components/Slider/Slider.jsx
src/components/Slider/Slider.md
src/components/Slider/__demo__/isSensitive.jsx
src/components/Slider/__demo__/numberInput.jsx
src/components/Slider/__demo__/numberInputTipFormatter.jsx
src/components/Slider/__demo__/slider.jsx
src/components/Slider/__tests__/__snapshots__/demo.test.js.snap
src/components/Slider/__tests__/__snapshots__/index.test.js.snap
src/components/Slider/__tests__/index.test.js
src/components/Slider/locale/en_US.js
src/components/Slider/locale/zh_CN.js

feature
add input tip
add support of locale
add isSensitive to control when to trigger onChange
add numberInputTipFormatter for format input tip
will not trigger onChange if value is change to same to current

feat(Slider): add tip when user input

---

src/components/Slider/Slider.jsx
src/components/Slider/__tests__/__snapshots__/index.test.js.snap
src/components/Slider/__tests__/index.test.js

feature
add onLastChange trigger when slide end or numberInput onNumberChange
No

feat(Slider): add onLastChange

---

CHANGELOG.md
package.json

chore(release): 0.3.3

---

src/components/LocaleProvider/__tests__/__snapshots__/index.test.js.snap
src/components/Table/Table.jsx
src/components/Table/Table.md
src/components/Table/__demo__/defaultExpandAllRows.jsx
src/components/Table/__demo__/expandedRowKeys.jsx
src/components/Table/__demo__/hideExpandIcon.jsx
src/components/Table/__demo__/onHeaderRow.jsx
src/components/Table/__demo__/onRow.jsx
src/components/Table/__tests__/__snapshots__/demo.test.js.snap
src/components/Table/style/index.js

feature
add hideExpandIcon to hide expandIcon
No

feat(Table): add hideExpandIcon

---

src/components/Table/Table.jsx

bug fix
pass function as TableRow component cause recreate
No

fix(Table): fix Table Row compnent allways recreate bug

---

src/components/Table/Table.jsx

bug fix
add onRow will override onRow in code
No

fix(Table): fix override of onRow affect contextMenu

---

src/components/Radio/Radio.jsx
src/components/Radio/__tests__/__snapshots__/demo.test.js.snap
src/components/Table/Table.jsx
src/components/Table/__demo__/rowSelection.jsx
src/components/Table/__tests__/__snapshots__/demo.test.js.snap
src/components/Table/__tests__/index.test.js

feature
set rowSelection.multiple to set table selection to single
No

feat(Table): add single select table selection

---

src/components/LocaleProvider/__tests__/__snapshots__/demo.test.js.snap
src/components/LocaleProvider/__tests__/__snapshots__/index.test.js.snap
src/components/Table/__tests__/__snapshots__/demo.test.js.snap
src/components/Table/style/index.js

bug fix
table missing background when x is scrollable
No

fix(Table): fix table missing background when x is scrollable

---

src/components/Table/ActionList.jsx

bug fix
disabled is not useful in menu
fix
No

fix(Table): fix table actionlist disable bug

---

.styleguide/setup.js
package.json
webpack.config.js
yarn.lock

feature
BREAKING CHANGE: must install styled-components in your project

feat(Package): move styles-components to peer & external

---

src/components/Badge/__tests__/__snapshots__/demo.test.js.snap
src/components/Button/__tests__/__snapshots__/demo.test.js.snap
src/components/Checkbox/__tests__/__snapshots__/demo.test.js.snap
src/components/Compact/__tests__/__snapshots__/demo.test.js.snap
src/components/DatePicker/__tests__/__snapshots__/demo.test.js.snap
src/components/Grid/__tests__/__snapshots__/demo.test.js.snap
src/components/Icon/__tests__/__snapshots__/demo.test.js.snap
src/components/Input/__tests__/__snapshots__/demo.test.js.snap
src/components/LocaleProvider/__tests__/__snapshots__/demo.test.js.snap
src/components/LocaleProvider/__tests__/__snapshots__/index.test.js.snap
src/components/Modal/__tests__/__snapshots__/demo.test.js.snap
src/components/Notice/__tests__/__snapshots__/demo.test.js.snap
src/components/NumberInput/__tests__/__snapshots__/demo.test.js.snap
src/components/Pagination/__tests__/__snapshots__/demo.test.js.snap
src/components/Radio/__tests__/__snapshots__/demo.test.js.snap
src/components/Radio/style/index.js
src/components/Select/__tests__/__snapshots__/demo.test.js.snap
src/components/Slider/__tests__/__snapshots__/demo.test.js.snap
src/components/Switch/__tests__/__snapshots__/demo.test.js.snap
src/components/Table/__tests__/__snapshots__/demo.test.js.snap
src/components/Tabs/__tests__/__snapshots__/demo.test.js.snap
src/components/Tooltip/__tests__/__snapshots__/demo.test.js.snap
src/components/ZForm/__tests__/__snapshots__/demo.test.js.snap

fix(Radio): fix radio card style

---

README.md

docs(Readme): update readme

---

src/components/Card/__tests__/__snapshots__/demo.test.js.snap
src/components/Card/style/index.js
yarn.lock

refactor
change card padding to bind :last-child

refactor(Card): rewrite card padding code

---

src/components/Tabs/__tests__/__snapshots__/demo.test.js.snap
src/components/Tabs/style/index.js

bug fix
tabs tab height is wrong
No

fix(Tabs): fix tabs tab height style bug

---

src/components/Tabs/Tabs.jsx
src/components/Tabs/__demo__/tabs-child.jsx
src/components/Tabs/__tests__/__snapshots__/demo.test.js.snap
src/components/Tabs/style/index.js

fix(Tabs): fix style bug when nest two diffrence styleType tabs

---

src/components/Tabs/__tests__/__snapshots__/demo.test.js.snap
src/components/Tabs/style/index.js

fix(Tabs): fix tabs tab bar style

---

src/components/Table/Table.jsx
src/components/Table/__tests__/__snapshots__/demo.test.js.snap

feat(Table): move footer outside of table content

---

.styleguide/components.json
.styleguide/setup.js
README.md
package.json
src/components/LocaleProvider/__tests__/__snapshots__/demo.test.js.snap
src/components/LocaleProvider/__tests__/__snapshots__/index.test.js.snap
src/components/Table/ResizableTH.jsx
src/components/Table/ResizableTH.md
src/components/Table/Table.jsx
src/components/Table/__demo__/resizableTH.jsx
src/components/Table/__tests__/__snapshots__/demo.test.js.snap
src/components/Table/style/index.js
yarn.lock

feature
add resizable table header
No

feat(Table): add resizableTH for table td resize

---

src/components/LocaleProvider/__tests__/__snapshots__/demo.test.js.snap
src/components/LocaleProvider/__tests__/__snapshots__/index.test.js.snap
src/components/Table/__tests__/__snapshots__/demo.test.js.snap
src/components/Table/style/index.js

bug fix
hidden scroll bar horz
No

fix(Table): fix scroll bar visible in windows

---

src/components/Badge/__tests__/__snapshots__/demo.test.js.snap
src/components/Button/__tests__/__snapshots__/demo.test.js.snap
src/components/Checkbox/__tests__/__snapshots__/demo.test.js.snap
src/components/Compact/__tests__/__snapshots__/demo.test.js.snap
src/components/Compact/style/index.js
src/components/DatePicker/__tests__/__snapshots__/demo.test.js.snap
src/components/Grid/__tests__/__snapshots__/demo.test.js.snap
src/components/Icon/__tests__/__snapshots__/demo.test.js.snap
src/components/Input/__tests__/__snapshots__/demo.test.js.snap
src/components/LocaleProvider/__tests__/__snapshots__/demo.test.js.snap
src/components/LocaleProvider/__tests__/__snapshots__/index.test.js.snap
src/components/Modal/__tests__/__snapshots__/demo.test.js.snap
src/components/Notice/__tests__/__snapshots__/demo.test.js.snap
src/components/NumberInput/__tests__/__snapshots__/demo.test.js.snap
src/components/Pagination/__tests__/__snapshots__/demo.test.js.snap
src/components/Radio/__tests__/__snapshots__/demo.test.js.snap
src/components/Radio/style/index.js
src/components/Select/__tests__/__snapshots__/demo.test.js.snap
src/components/Slider/__tests__/__snapshots__/demo.test.js.snap
src/components/Switch/__tests__/__snapshots__/demo.test.js.snap
src/components/Table/__tests__/__snapshots__/demo.test.js.snap
src/components/Tabs/__tests__/__snapshots__/demo.test.js.snap
src/components/Tooltip/__tests__/__snapshots__/demo.test.js.snap
src/components/ZForm/__tests__/__snapshots__/demo.test.js.snap

fix(All): fix zindex override bug

---

src/components/Table/ActionList.jsx
src/components/Table/__demo__/actionList.jsx
src/components/Table/__tests__/__snapshots__/demo.test.js.snap

feature
add button styleType to actionList
No

feat(Table): add button styleType to actionList

---

src/components/Badge/__tests__/__snapshots__/demo.test.js.snap
src/components/Button/__tests__/__snapshots__/demo.test.js.snap
src/components/Checkbox/__tests__/__snapshots__/demo.test.js.snap
src/components/Compact/__tests__/__snapshots__/demo.test.js.snap
src/components/DatePicker/__tests__/__snapshots__/demo.test.js.snap
src/components/Form/Group.jsx
src/components/Form/__demo__/group.jsx
src/components/Form/__tests__/__snapshots__/demo.test.js.snap
src/components/Grid/__tests__/__snapshots__/demo.test.js.snap
src/components/Icon/__tests__/__snapshots__/demo.test.js.snap
src/components/Input/__tests__/__snapshots__/demo.test.js.snap
src/components/LocaleProvider/__tests__/__snapshots__/demo.test.js.snap
src/components/LocaleProvider/__tests__/__snapshots__/index.test.js.snap
src/components/Modal/__tests__/__snapshots__/demo.test.js.snap
src/components/Notice/__tests__/__snapshots__/demo.test.js.snap
src/components/NumberInput/__tests__/__snapshots__/demo.test.js.snap
src/components/Pagination/__tests__/__snapshots__/demo.test.js.snap
src/components/Radio/Radio.jsx
src/components/Radio/__tests__/__snapshots__/demo.test.js.snap
src/components/Radio/style/index.js
src/components/Select/__tests__/__snapshots__/demo.test.js.snap
src/components/Slider/__tests__/__snapshots__/demo.test.js.snap
src/components/Switch/__tests__/__snapshots__/demo.test.js.snap
src/components/Table/__tests__/__snapshots__/demo.test.js.snap
src/components/Tabs/Tabs.jsx
src/components/Tabs/__tests__/__snapshots__/demo.test.js.snap
src/components/Tabs/style/index.js
src/components/ThemeProvider/material.js
src/components/Tooltip/__tests__/__snapshots__/demo.test.js.snap
src/components/ZForm/__tests__/__snapshots__/demo.test.js.snap

feat(Radio): add classnames

---

src/components/Modal/__demo__/method.jsx
src/components/Modal/__tests__/__snapshots__/demo.test.js.snap
src/components/Modal/method.jsx

feature
support promise when use modal method onOk onClose
No

feat(Modal): support promise when use modal method

---

src/components/Textarea/__tests__/__snapshots__/demo.test.js.snap
src/components/Textarea/style/index.js

bug fix
add placeholder color of Textarea

fix(Textarea): fix placeholder color

---

src/components/Badge/__tests__/__snapshots__/demo.test.js.snap
src/components/Compact/__tests__/__snapshots__/demo.test.js.snap
src/components/DatePicker/__tests__/__snapshots__/demo.test.js.snap
src/components/Form/__tests__/__snapshots__/demo.test.js.snap
src/components/Input/Input.jsx
src/components/Input/__tests__/__snapshots__/demo.test.js.snap
src/components/Input/style/index.js
src/components/LocaleProvider/__tests__/__snapshots__/demo.test.js.snap
src/components/LocaleProvider/__tests__/__snapshots__/index.test.js.snap
src/components/NumberInput/__tests__/__snapshots__/demo.test.js.snap
src/components/Select/__tests__/__snapshots__/demo.test.js.snap
src/components/Switch/__tests__/__snapshots__/demo.test.js.snap
src/components/Table/__tests__/__snapshots__/demo.test.js.snap

feature
add classname of input
No

feat(Input): add classname

---

src/components/Slider/Slider.jsx

bug fix
display wrong when update max min or step
No

fix(Slider): fix slider bug when update max min or step

---

src/components/LocaleProvider/__tests__/__snapshots__/index.test.js.snap
src/components/Select/style/index.js

bug fix
fix search input width and menu max width

fix(Select): fix search input width and menu max width

---

src/components/Card/__tests__/__snapshots__/demo.test.js.snap
src/components/Card/style/index.js

feat(Card): remove min height of card content

---

src/components/DatePicker/__tests__/__snapshots__/demo.test.js.snap
src/components/NumberInput/__tests__/__snapshots__/demo.test.js.snap
src/components/NumberInput/style/index.js
src/components/Slider/__tests__/__snapshots__/demo.test.js.snap
src/components/ThemeProvider/material.js

fix(NumberInput): fix style of suffix

---

src/components/Badge/__tests__/__snapshots__/demo.test.js.snap
src/components/Button/__tests__/__snapshots__/demo.test.js.snap
src/components/Checkbox/__tests__/__snapshots__/demo.test.js.snap
src/components/Compact/__tests__/__snapshots__/demo.test.js.snap
src/components/DatePicker/__tests__/__snapshots__/demo.test.js.snap
src/components/Grid/__tests__/__snapshots__/demo.test.js.snap
src/components/Icon/__tests__/__snapshots__/demo.test.js.snap
src/components/Input/__tests__/__snapshots__/demo.test.js.snap
src/components/LocaleProvider/__tests__/__snapshots__/demo.test.js.snap
src/components/LocaleProvider/__tests__/__snapshots__/index.test.js.snap
src/components/Modal/__tests__/__snapshots__/demo.test.js.snap
src/components/Notice/__tests__/__snapshots__/demo.test.js.snap
src/components/NumberInput/__tests__/__snapshots__/demo.test.js.snap
src/components/Pagination/__tests__/__snapshots__/demo.test.js.snap
src/components/Radio/Radio.jsx
src/components/Radio/__tests__/__snapshots__/demo.test.js.snap
src/components/Radio/style/index.js
src/components/Select/__tests__/__snapshots__/demo.test.js.snap
src/components/Slider/__tests__/__snapshots__/demo.test.js.snap
src/components/Switch/__tests__/__snapshots__/demo.test.js.snap
src/components/Table/__tests__/__snapshots__/demo.test.js.snap
src/components/Tabs/__tests__/__snapshots__/demo.test.js.snap
src/components/Tooltip/__tests__/__snapshots__/demo.test.js.snap
src/components/ZForm/__tests__/__snapshots__/demo.test.js.snap

feat(Radio): add text radio

---

src/components/Checkbox/Checkbox.jsx
src/components/Checkbox/__demo__/checkbox-styleType.jsx
src/components/Checkbox/__tests__/__snapshots__/demo.test.js.snap
src/components/Radio/Card.jsx
src/components/Radio/__tests__/__snapshots__/demo.test.js.snap
src/components/Radio/style/index.js

feat(Radio): change card style

---

src/components/Compact/__tests__/__snapshots__/demo.test.js.snap
src/components/DatePicker/__tests__/__snapshots__/demo.test.js.snap
src/components/LocaleProvider/__tests__/__snapshots__/demo.test.js.snap
src/components/LocaleProvider/__tests__/__snapshots__/index.test.js.snap
src/components/Pagination/__tests__/__snapshots__/demo.test.js.snap
src/components/Select/__tests__/__snapshots__/demo.test.js.snap
src/components/Select/style/index.js
src/components/Table/__tests__/__snapshots__/demo.test.js.snap
src/components/ZForm/__tests__/__snapshots__/demo.test.js.snap

feat(Select): reduce padding of select

---

src/components/Card/Card.md
src/components/Card/__demo__/single.jsx
src/components/Card/__tests__/__snapshots__/demo.test.js.snap
src/components/Card/style/index.js

feat(Card): update card style

---

src/components/Checkbox/__tests__/__snapshots__/demo.test.js.snap
src/components/LocaleProvider/__tests__/__snapshots__/demo.test.js.snap
src/components/LocaleProvider/__tests__/__snapshots__/index.test.js.snap
src/components/Radio/__tests__/__snapshots__/demo.test.js.snap
src/components/Radio/style/index.js
src/components/ZForm/__tests__/__snapshots__/demo.test.js.snap

feat(Radio): change radio min-width size

---

src/components/Button/style/index.js
src/components/Checkbox/__tests__/__snapshots__/demo.test.js.snap
src/components/LocaleProvider/__tests__/__snapshots__/demo.test.js.snap
src/components/LocaleProvider/__tests__/__snapshots__/index.test.js.snap
src/components/Radio/__tests__/__snapshots__/demo.test.js.snap
src/components/Radio/style/index.js
src/components/ZForm/__tests__/__snapshots__/demo.test.js.snap

feat(All): change some style

---

src/components/Form/__tests__/__snapshots__/demo.test.js.snap
src/components/LocaleProvider/__tests__/__snapshots__/demo.test.js.snap
src/components/LocaleProvider/__tests__/__snapshots__/index.test.js.snap
src/components/Slider/Slider.jsx
src/components/Slider/__demo__/marks.jsx
src/components/Slider/__tests__/__snapshots__/demo.test.js.snap
src/components/Slider/__tests__/__snapshots__/index.test.js.snap
src/components/Slider/style/index.js

feat(Slider): change slider wrap

---

src/components/DatePicker/Range.jsx
src/components/DatePicker/locale/en_US.js
src/components/DatePicker/locale/zh_CN.js
src/components/DatePicker/style/index.js
src/components/DatePicker/utils.js

feat(DatePicker): add rangeTip & some error tips

---

src/components/LocaleProvider/__tests__/__snapshots__/index.test.js.snap
src/components/Slider/__tests__/__snapshots__/index.test.js.snap
src/components/Tooltip/Tooltip.jsx
src/components/Tooltip/__tests__/__snapshots__/demo.test.js.snap
src/components/Tooltip/__tests__/__snapshots__/index.test.js.snap
src/components/Tooltip/style/index.js

fix(Tooltip): fix tooltip auto align style

---

src/components/Badge/__tests__/__snapshots__/demo.test.js.snap
src/components/Button/__tests__/__snapshots__/demo.test.js.snap
src/components/Checkbox/__tests__/__snapshots__/demo.test.js.snap
src/components/Collapse/__tests__/__snapshots__/demo.test.js.snap
src/components/Compact/__tests__/__snapshots__/demo.test.js.snap
src/components/DatePicker/__tests__/__snapshots__/demo.test.js.snap
src/components/Form/__tests__/__snapshots__/demo.test.js.snap
src/components/Grid/__tests__/__snapshots__/demo.test.js.snap
src/components/Icon/__tests__/__snapshots__/demo.test.js.snap
src/components/Input/__tests__/__snapshots__/demo.test.js.snap
src/components/Loading/__tests__/__snapshots__/demo.test.js.snap
src/components/LocaleProvider/__tests__/__snapshots__/demo.test.js.snap
src/components/LocaleProvider/__tests__/__snapshots__/index.test.js.snap
src/components/Menu/__tests__/__snapshots__/demo.test.js.snap
src/components/Modal/__tests__/__snapshots__/demo.test.js.snap
src/components/Notice/__tests__/__snapshots__/demo.test.js.snap
src/components/NumberInput/__tests__/__snapshots__/demo.test.js.snap
src/components/Pagination/__tests__/__snapshots__/demo.test.js.snap
src/components/Radio/__tests__/__snapshots__/demo.test.js.snap
src/components/Select/__tests__/__snapshots__/demo.test.js.snap
src/components/Slider/__tests__/__snapshots__/demo.test.js.snap
src/components/Slider/__tests__/__snapshots__/index.test.js.snap
src/components/Switch/__tests__/__snapshots__/demo.test.js.snap
src/components/Table/__tests__/__snapshots__/demo.test.js.snap
src/components/Tabs/__tests__/__snapshots__/demo.test.js.snap
src/components/Textarea/__tests__/__snapshots__/demo.test.js.snap
src/components/ThemeProvider/color.js
src/components/Upload/__tests__/__snapshots__/demo.test.js.snap
src/components/ZForm/__tests__/__snapshots__/demo.test.js.snap

feat(style): change active border color

---

src/components/DatePicker/DatePicker.jsx
src/components/DatePicker/Month.jsx

feat(DatePicker): fix change error

---

CHANGELOG.md
src/components/Calendar/__tests__/__snapshots__/demo.test.js.snap
src/components/Calendar/style/index.js
src/components/LocaleProvider/__tests__/__snapshots__/demo.test.js.snap
src/components/LocaleProvider/__tests__/__snapshots__/index.test.js.snap

fix(Calendar): fix calendar cell disabled style when current & active

---

src/components/LocaleProvider/__tests__/__snapshots__/demo.test.js.snap
src/components/LocaleProvider/__tests__/__snapshots__/index.test.js.snap
src/components/Table/__tests__/__snapshots__/demo.test.js.snap
src/components/Table/style/index.js

feat(Table): add style for title to avoid cover of table

---

.styleguide/components.json
package.json
src/components/Drawer/Drawer.jsx
src/components/Drawer/Drawer.md
src/components/Drawer/__demo__/destroyOnClose.jsx
src/components/Drawer/__demo__/drawer.jsx
src/components/Drawer/__demo__/getContainer.jsx
src/components/Drawer/__demo__/multiple.jsx
src/components/Drawer/__demo__/placement.jsx
src/components/Drawer/index.jsx
src/components/Drawer/style/index.js
src/style/globalAnimation.js
yarn.lock

feat(Drawer): add Drawer

---

src/components/Button/__tests__/__snapshots__/demo.test.js.snap
src/components/Button/style/index.js
src/components/Checkbox/Checkbox.jsx
src/components/Checkbox/__tests__/__snapshots__/demo.test.js.snap
src/components/Checkbox/style/index.js
src/components/Input/Search.jsx
src/components/Input/__tests__/__snapshots__/demo.test.js.snap
src/components/Input/style/index.js
src/components/LocaleProvider/__tests__/__snapshots__/demo.test.js.snap
src/components/LocaleProvider/__tests__/__snapshots__/index.test.js.snap
src/components/Radio/Radio.jsx
src/components/Radio/__tests__/__snapshots__/demo.test.js.snap
src/components/Radio/style/index.js
src/components/Switch/Switch.jsx
src/components/Switch/__tests__/__snapshots__/demo.test.js.snap
src/components/Switch/style/index.js
src/components/Table/__tests__/__snapshots__/demo.test.js.snap
src/components/Upload/__tests__/__snapshots__/demo.test.js.snap
src/components/ZForm/__tests__/__snapshots__/demo.test.js.snap

feat(All): remove some pointer-event none

---

src/components/Table/Table.jsx
src/components/Table/__demo__/subTable.jsx
src/components/Table/__tests__/__snapshots__/demo.test.js.snap
src/components/Table/__tests__/index.test.js

feat(Table): support selectAll of children & add expandIconColumnIndex

---

src/components/Checkbox/__tests__/__snapshots__/demo.test.js.snap
src/components/Radio/Card.jsx
src/components/Radio/__demo__/group-styleType.jsx
src/components/Radio/__demo__/radio-styleType.jsx
src/components/Radio/__tests__/__snapshots__/demo.test.js.snap

feat(Radio): change card style when title is null

---

package.json
src/components/Drawer/Drawer.jsx
src/components/Drawer/__demo__/destroyOnClose.jsx
src/components/Drawer/__demo__/drawer.jsx
src/components/Drawer/style/index.js
src/libs/rc-drawer/Drawer.js
src/libs/rc-drawer/LICENSE.md
src/libs/rc-drawer/README.md
src/libs/rc-drawer/index.js
src/libs/rc-drawer/utils.js
yarn.lock

fix(Drawer): fix Drawer unmount not trigger bug

---

src/components/Button/Button.jsx
src/components/Button/Button.md
src/components/Button/__demo__/button.jsx
src/components/Button/__demo__/fakeDisabled.jsx
src/components/Button/__tests__/__snapshots__/demo.test.js.snap
src/components/Button/style/index.js
src/components/Table/__tests__/__snapshots__/demo.test.js.snap
src/components/Upload/__tests__/__snapshots__/demo.test.js.snap

feat(Button): add fakeDisabled to avoid disabled button wrong usage

---

src/components/LocaleProvider/__tests__/__snapshots__/demo.test.js.snap
src/components/LocaleProvider/__tests__/__snapshots__/index.test.js.snap
src/components/Table/__tests__/__snapshots__/demo.test.js.snap
src/components/Table/style/index.js

feat(Table): remove table content overflow style

---

src/components/LocaleProvider/__tests__/__snapshots__/demo.test.js.snap
src/components/LocaleProvider/__tests__/__snapshots__/index.test.js.snap
src/components/Table/__tests__/__snapshots__/demo.test.js.snap
src/components/Table/style/index.js

fix(Table): add clear both to table content to fix title float

---

src/components/LocaleProvider/__tests__/__snapshots__/demo.test.js.snap
src/components/LocaleProvider/__tests__/__snapshots__/index.test.js.snap
src/components/Table/ExpandedRowContent.jsx
src/components/Table/Table.jsx
src/components/Table/__demo__/expandedRowRender.jsx
src/components/Table/__tests__/__snapshots__/demo.test.js.snap
src/components/Table/index.jsx
src/components/Table/style/index.js

feat(Table): add ExpandedRowContent|remove border of action icon

---

src/components/LocaleProvider/__tests__/__snapshots__/demo.test.js.snap
src/components/LocaleProvider/__tests__/__snapshots__/index.test.js.snap
src/components/Table/Table.jsx
src/components/Table/__demo__/table.jsx
src/components/Table/__tests__/__snapshots__/demo.test.js.snap
src/components/Table/style/index.js

feat(Table): add zebraCrossing

---

package.json
src/components/Form/__tests__/__snapshots__/demo.test.js.snap
src/components/LocaleProvider/__tests__/__snapshots__/demo.test.js.snap
src/components/LocaleProvider/__tests__/__snapshots__/index.test.js.snap
src/components/Slider/Slider.jsx
src/components/Slider/__tests__/__snapshots__/demo.test.js.snap
src/components/Slider/__tests__/__snapshots__/index.test.js.snap
src/components/Slider/style/index.js
yarn.lock

fix(Slider): fix slider click offset when horiz scrolled

---

package.json
yarn.lock

fix(Modal): fix version of rc-dialog to avoid bug

---

src/components/Table/Table.jsx
src/components/Table/Table.md
src/components/Table/__demo__/doNotHandleCondition.jsx
src/components/Table/__demo__/fullRemoteTable.jsx
src/components/Table/__demo__/onConditionChange.jsx
src/components/Table/__tests__/__snapshots__/demo.test.js.snap

feat(Table): add onConditionChange & doNotHandleConditionChange

---

src/components/LocaleProvider/__tests__/__snapshots__/index.test.js.snap
src/components/LocaleProvider/__tests__/index.test.js
src/components/Pagination/__tests__/index.test.js
src/components/Popover/Popover.jsx
src/components/Popover/__demo__/control.jsx
src/components/Popover/__tests__/__snapshots__/demo.test.js.snap
src/components/Popover/__tests__/__snapshots__/index.test.js.snap
src/components/Slider/__tests__/__snapshots__/index.test.js.snap
src/components/Tooltip/__tests__/__snapshots__/demo.test.js.snap
src/components/Tooltip/__tests__/__snapshots__/index.test.js.snap

bug fix
*   [x] Docs have been added/updated

fix(Popover): fix popover scroll bar blur when scroll

---

src/components/Table/Table.jsx
src/components/Table/Table.md
src/components/Table/__demo__/columns.jsx
src/components/Table/__tests__/__snapshots__/demo.test.js.snap

feat(Table): add column.renderTitle & some docs

---

src/components/Table/__demo__/table.jsx
src/components/Table/__tests__/__snapshots__/demo.test.js.snap

docs(Table): fix table demo overflow bug

---

src/components/Message/MessageContainer.jsx

fix(Message): fix message onClose not trigger bug

---

src/components/LocaleProvider/__demo__/list.jsx
src/components/LocaleProvider/__tests__/__snapshots__/demo.test.js.snap
src/components/LocaleProvider/__tests__/__snapshots__/index.test.js.snap
src/components/Pagination/Pagination.jsx
src/components/Pagination/Pagination.md
src/components/Pagination/__demo__/pagination.jsx
src/components/Pagination/__demo__/showTotal.jsx
src/components/Pagination/__tests__/__snapshots__/demo.test.js.snap
src/components/Pagination/locale/en_US.js
src/components/Pagination/locale/zh_CN.js
src/components/Pagination/style/index.js
src/components/Table/__tests__/__snapshots__/demo.test.js.snap

feat(Pagination): add showTotal

---

src/components/Checkbox/Checkbox.jsx
src/components/Checkbox/__tests__/__snapshots__/demo.test.js.snap
src/components/Checkbox/style/index.js
src/components/Collapse/__tests__/__snapshots__/demo.test.js.snap
src/components/LocaleProvider/__tests__/__snapshots__/demo.test.js.snap
src/components/LocaleProvider/__tests__/__snapshots__/index.test.js.snap
src/components/Menu/__tests__/__snapshots__/demo.test.js.snap
src/components/Table/__tests__/__snapshots__/demo.test.js.snap

feat(Checkbox): add support of multiple content

---

.styleguide/setup.js
index.js
package.json
src/components/Badge/__tests__/__snapshots__/demo.test.js.snap
src/components/Compact/__tests__/__snapshots__/demo.test.js.snap
src/components/DatePicker/__tests__/__snapshots__/demo.test.js.snap
src/components/Form/__tests__/__snapshots__/demo.test.js.snap
src/components/Input/Input.jsx
src/components/Input/Input.md
src/components/Input/Search.jsx
src/components/Input/Search.md
src/components/Input/__demo__/input-disabled.jsx
src/components/Input/__demo__/input-prefix.jsx
src/components/Input/__demo__/input-suffix.jsx
src/components/Input/__demo__/input.jsx
src/components/Input/__demo__/search-disabled.jsx
src/components/Input/__tests__/__snapshots__/demo.test.js.snap
src/components/Input/style/index.js
src/components/LocaleProvider/__tests__/__snapshots__/demo.test.js.snap
src/components/LocaleProvider/__tests__/__snapshots__/index.test.js.snap
src/components/NumberInput/__tests__/__snapshots__/demo.test.js.snap
src/components/Select/__tests__/__snapshots__/demo.test.js.snap
src/components/Switch/__tests__/__snapshots__/demo.test.js.snap
src/components/Table/__tests__/__snapshots__/demo.test.js.snap
yarn.lock

feat(Input): add suffix & prefix & click to focus

---

src/components/Badge/__tests__/__snapshots__/demo.test.js.snap
src/components/Compact/__tests__/__snapshots__/demo.test.js.snap
src/components/DatePicker/__tests__/__snapshots__/demo.test.js.snap
src/components/Form/__tests__/__snapshots__/demo.test.js.snap
src/components/Input/Input.jsx
src/components/Input/__tests__/__snapshots__/demo.test.js.snap
src/components/Input/style/index.js
src/components/LocaleProvider/__tests__/__snapshots__/demo.test.js.snap
src/components/LocaleProvider/__tests__/__snapshots__/index.test.js.snap
src/components/NumberInput/__tests__/__snapshots__/demo.test.js.snap
src/components/Select/__tests__/__snapshots__/demo.test.js.snap
src/components/Switch/__tests__/__snapshots__/demo.test.js.snap
src/components/Table/__tests__/__snapshots__/demo.test.js.snap

fix(Input): fix missing onFocus & onBlur & override default style

---

src/components/Menu/Menu.jsx
src/components/Message/Message.jsx
src/components/Message/method.jsx
src/components/Notice/Notice.jsx
src/components/Select/Select.jsx
src/components/Table/Table.jsx

feat(deprecatedLog): change deprecated log to called only once

---

src/components/Tabs/__tests__/__snapshots__/demo.test.js.snap
src/components/Tabs/style/index.js

fix(Tabs): fix nested tabs style bug

---

src/components/Radio/Radio.md

docs(Radio): add docs for use Tooltip with radio button disabled

---

src/components/Input/Input.jsx
src/components/Input/Input.md
src/components/Input/__demo__/input-status.jsx
src/components/Input/__tests__/__snapshots__/demo.test.js.snap
src/components/Input/style/index.js
src/components/LocaleProvider/__tests__/__snapshots__/index.test.js.snap

feat(Input): add error status

---

src/components/LocaleProvider/__tests__/__snapshots__/index.test.js.snap
src/components/LocaleProvider/__tests__/index.test.js
src/components/Table/Table.jsx

feat(Table): remove border of search tip

---

src/components/LocaleProvider/__tests__/__snapshots__/demo.test.js.snap
src/components/LocaleProvider/__tests__/__snapshots__/index.test.js.snap
src/components/Table/__tests__/__snapshots__/demo.test.js.snap
src/components/Table/style/index.js

feature
*   [X ] Follow our contributing docs

feat(Table): change box-shadow of fixed table

---

src/components/Checkbox/__tests__/__snapshots__/demo.test.js.snap
src/components/Checkbox/style/index.js
src/components/Collapse/__tests__/__snapshots__/demo.test.js.snap
src/components/LocaleProvider/__tests__/__snapshots__/demo.test.js.snap
src/components/LocaleProvider/__tests__/__snapshots__/index.test.js.snap
src/components/Menu/__tests__/__snapshots__/demo.test.js.snap
src/components/Table/__tests__/__snapshots__/demo.test.js.snap

feat(Checkbox): change checkbox icon color

---

src/components/ZForm/__demo__/uhost.jsx
src/components/ZForm/__tests__/__snapshots__/demo.test.js.snap

docs(ZFrom): fix bug in form demo

---

src/components/Breadcrumb/Breadcrumb.jsx
src/components/Breadcrumb/Breadcrumb.md
src/components/Breadcrumb/__demo__/breadcrumb-styleType.jsx
src/components/Breadcrumb/__demo__/breadcrumb.jsx
src/components/Breadcrumb/__tests__/__snapshots__/demo.test.js.snap
src/components/Breadcrumb/style/index.js

feat(Breadcrumb): add styleType

---

src/components/Badge/__tests__/__snapshots__/demo.test.js.snap
src/components/Breadcrumb/__tests__/__snapshots__/demo.test.js.snap
src/components/Button/__tests__/__snapshots__/demo.test.js.snap
src/components/Checkbox/__tests__/__snapshots__/demo.test.js.snap
src/components/Compact/__tests__/__snapshots__/demo.test.js.snap
src/components/DatePicker/__tests__/__snapshots__/demo.test.js.snap
src/components/Form/__tests__/__snapshots__/demo.test.js.snap
src/components/Grid/__tests__/__snapshots__/demo.test.js.snap
src/components/Icon/__tests__/__snapshots__/demo.test.js.snap
src/components/Input/__tests__/__snapshots__/demo.test.js.snap
src/components/Modal/__tests__/__snapshots__/demo.test.js.snap
src/components/Notice/__tests__/__snapshots__/demo.test.js.snap
src/components/NumberInput/__tests__/__snapshots__/demo.test.js.snap
src/components/Pagination/__tests__/__snapshots__/demo.test.js.snap
src/components/Radio/Radio.jsx
src/components/Radio/__tests__/__snapshots__/demo.test.js.snap
src/components/Select/__tests__/__snapshots__/demo.test.js.snap
src/components/Slider/__tests__/__snapshots__/demo.test.js.snap
src/components/Switch/__tests__/__snapshots__/demo.test.js.snap
src/components/Table/__tests__/__snapshots__/demo.test.js.snap
src/components/Table/__tests__/index.test.js
src/components/Tabs/__tests__/__snapshots__/demo.test.js.snap
src/components/Tooltip/__tests__/__snapshots__/demo.test.js.snap

feat(Radio): change icon for radio

---

src/components/Badge/__tests__/__snapshots__/demo.test.js.snap
src/components/Collapse/__tests__/__snapshots__/demo.test.js.snap
src/components/DatePicker/__tests__/__snapshots__/demo.test.js.snap
src/components/Form/__tests__/__snapshots__/demo.test.js.snap
src/components/Grid/__tests__/__snapshots__/demo.test.js.snap
src/components/Icon/__tests__/__snapshots__/demo.test.js.snap
src/components/LocaleProvider/__tests__/__snapshots__/demo.test.js.snap
src/components/LocaleProvider/__tests__/__snapshots__/index.test.js.snap
src/components/Modal/__tests__/__snapshots__/demo.test.js.snap
src/components/NumberInput/__tests__/__snapshots__/demo.test.js.snap
src/components/NumberInput/style/index.js
src/components/Pagination/__tests__/__snapshots__/demo.test.js.snap
src/components/Progress/__tests__/__snapshots__/demo.test.js.snap
src/components/Slider/__tests__/__snapshots__/demo.test.js.snap
src/components/Slider/__tests__/__snapshots__/index.test.js.snap
src/components/Table/__tests__/__snapshots__/demo.test.js.snap
src/components/Tabs/__tests__/__snapshots__/demo.test.js.snap

fix(NumberInput): fix height in IE

---

.styleguide/components.json
src/components/SvgIcon/SvgIcon.jsx
src/components/SvgIcon/SvgIcon.md
src/components/SvgIcon/__demo__/svgIcon-color.jsx
src/components/SvgIcon/__demo__/svgIcon-size.jsx
src/components/SvgIcon/__demo__/svgIcon-spin.jsx
src/components/SvgIcon/__demo__/svgIcon-type.jsx
src/components/SvgIcon/__demo__/svgIcon.jsx
src/components/SvgIcon/__tests__/__snapshots__/demo.test.js.snap
src/components/SvgIcon/__tests__/demo.test.js
src/components/SvgIcon/icons/CircleLoading.jsx
src/components/SvgIcon/icons/Cross.jsx
src/components/SvgIcon/icons/DottedRightArrow.jsx
src/components/SvgIcon/icons/Tick.jsx
src/components/SvgIcon/index.jsx
src/components/SvgIcon/style/index.js

feat(SvgIcon): add SvgIcon

---

src/components/DatePicker/__tests__/__snapshots__/demo.test.js.snap
src/components/Input/__tests__/__snapshots__/demo.test.js.snap
src/components/Input/style/index.js
src/components/NumberInput/__tests__/__snapshots__/demo.test.js.snap
src/components/NumberInput/style/index.js
src/components/Slider/__tests__/__snapshots__/demo.test.js.snap

fix(Input): fix input disabled color in safari

---

src/components/Icon/Icon.jsx
src/components/Icon/Icon.md

feat(Icon): add prefix to support custom font-icon

---

src/components/Drawer/Drawer.jsx
src/components/Drawer/Drawer.md
src/components/Drawer/__demo__/closeHandler.jsx
src/components/Drawer/__demo__/drawer.jsx
src/components/Drawer/style/index.js
src/components/SvgIcon/SvgIcon.jsx
src/components/SvgIcon/__tests__/__snapshots__/demo.test.js.snap
src/components/SvgIcon/icons/BoldCross.jsx
src/components/ThemeProvider/color.js
src/libs/rc-drawer/Drawer.js
src/style/globalAnimation.js

feat(Drawer): add close handler

---

src/components/NumberInput/__tests__/__snapshots__/demo.test.js.snap
src/components/NumberInput/style/index.js

fix(NumberInput): fix border when hideHandler

---

package.json
src/components/LocaleProvider/__tests__/__snapshots__/demo.test.js.snap
src/components/LocaleProvider/__tests__/__snapshots__/index.test.js.snap
src/components/Table/Table.jsx
src/components/Table/__demo__/table.jsx
src/components/Table/__tests__/__snapshots__/demo.test.js.snap
src/components/Table/style/index.js
src/libs/rc-table/BaseTable.js
src/libs/rc-table/BodyTable.js
src/libs/rc-table/ColGroup.js
src/libs/rc-table/Column.js
src/libs/rc-table/ColumnGroup.js
src/libs/rc-table/ColumnManager.js
src/libs/rc-table/ExpandIcon.js
src/libs/rc-table/ExpandableRow.js
src/libs/rc-table/ExpandableTable.js
src/libs/rc-table/HeadTable.js
src/libs/rc-table/LICENSE.md
src/libs/rc-table/README.md
src/libs/rc-table/Table.js
src/libs/rc-table/TableCell.js
src/libs/rc-table/TableHeader.js
src/libs/rc-table/TableHeaderRow.js
src/libs/rc-table/TableRow.js
src/libs/rc-table/index.js
src/libs/rc-table/utils.js
yarn.lock

add columnPlaceholder for auto placehold with & clone table to local
feature

feat(Table): add columnPlaceholder

---

src/components/Tabs/__tests__/__snapshots__/demo.test.js.snap
src/components/Tabs/style/index.js

feat(Tabs): remove point-event:none in disabled tab

---

src/components/Menu/__tests__/__snapshots__/demo.test.js.snap
src/components/Menu/style/index.js

feat(Menu): remove pointer-event:none of menu item

---

src/components/LocaleProvider/__tests__/__snapshots__/demo.test.js.snap
src/components/LocaleProvider/__tests__/__snapshots__/index.test.js.snap
src/components/Table/Table.jsx
src/components/Table/__tests__/__snapshots__/demo.test.js.snap
src/components/Table/style/index.js
src/components/ThemeProvider/color.js

feat(Table): add cable for table child td

---

src/components/Compact/__tests__/__snapshots__/demo.test.js.snap
src/components/DatePicker/__tests__/__snapshots__/demo.test.js.snap
src/components/Form/__tests__/__snapshots__/demo.test.js.snap
src/components/LocaleProvider/__tests__/__snapshots__/demo.test.js.snap
src/components/LocaleProvider/__tests__/__snapshots__/index.test.js.snap
src/components/Pagination/__tests__/__snapshots__/demo.test.js.snap
src/components/Select/__tests__/__snapshots__/demo.test.js.snap
src/components/Select/style/index.js
src/components/Table/__tests__/__snapshots__/demo.test.js.snap
src/components/ZForm/__tests__/__snapshots__/demo.test.js.snap

fix(Select): fix selector styles

---

src/components/Modal/Modal.jsx
src/components/Modal/style/index.js

fix(Modal): fix modal hide-mask style

---

src/components/DatePicker/style/index.js

fix(DatePicker): change month wrapper width to 240

---

src/components/Tooltip/Tooltip.jsx
src/components/Tooltip/Tooltip.md
src/components/Tooltip/__demo__/arrow.jsx
src/components/Tooltip/__demo__/tooltip.jsx
src/components/Tooltip/__tests__/__snapshots__/demo.test.js.snap

feat(Tooltip): add arrow props to hide arrow

---

src/components/LocaleProvider/__tests__/__snapshots__/index.test.js.snap
src/components/Table/Table.jsx

feat(Table): change table tip notice to default

---

src/components/Input/__tests__/__snapshots__/demo.test.js.snap
src/components/Input/style/index.js

fix(Input): fix input placeholder color when disable

---

src/components/Slider/Slider.jsx
src/components/ZForm/ZForm.md

fix(Slider): fix slider bug when key props change

---

src/components/Steps/__tests__/__snapshots__/demo.test.js.snap
src/components/Steps/style/index.js

feat(Step): add designTokens to step

---

.prettierrc
src/components/Table/Table.jsx

feat(Table): move columnPlaceholder before lastest fix column

---

src/components/LocaleProvider/__tests__/__snapshots__/demo.test.js.snap
src/components/LocaleProvider/__tests__/__snapshots__/index.test.js.snap
src/components/Table/Table.jsx
src/components/Table/__demo__/filter.jsx
src/components/Table/__tests__/__snapshots__/demo.test.js.snap
src/components/Table/style/index.js

feat(Table): add support of controlled filter

---

src/components/Popover/Popover.jsx
src/components/Table/Table.jsx
src/components/Table/__demo__/columns.jsx
src/components/Tooltip/Tooltip.md

docs(All): update some docs

---

src/components/Table/Table.jsx
src/components/Table/__demo__/emptyContent.jsx
src/components/Table/__demo__/errorContent.jsx
src/components/Table/__demo__/groupColumns.jsx

feat(Table): add warning to missing column key

---

src/components/Progress/Progress.jsx
src/components/Progress/__tests__/__snapshots__/demo.test.js.snap
src/components/Progress/style/index.js

feat(Progress): move out top text & hide overflow progress

---

src/components/Table/Table.jsx
src/components/Table/__demo__/order.jsx
src/components/Table/__demo__/scroll.jsx
src/components/Table/__tests__/__snapshots__/demo.test.js.snap

feat(Table): add controlled order & default order

---

src/components/Message/Message.jsx
src/components/Message/Message.md
src/components/Message/__demo__/base.jsx
src/components/Message/__demo__/custom.jsx
src/components/Message/method.jsx
src/components/Message/style/index.js
src/components/Table/Table.jsx

feat(Message): add custom popup method

---

src/components/Table/Table.jsx

feat(Table): change empty column warn to false columns

---

src/components/Message/Message.md
src/components/Message/MessageContainer.jsx
src/components/Message/__demo__/config.jsx
src/components/Message/method.jsx

feat(Message): add config

---

src/components/Drawer/style/index.js

feat(Drawer): change drawer icon

---

src/components/Upload/Upload.jsx
src/components/Upload/Upload.md
src/components/Upload/__demo__/accept.jsx
src/components/Upload/__demo__/base.jsx
src/components/Upload/__demo__/controlled.jsx
src/components/Upload/__demo__/listType.jsx
src/components/Upload/__demo__/maxSize.jsx
src/components/Upload/__demo__/readFile.jsx
src/components/Upload/__demo__/selector.jsx
src/components/Upload/__demo__/single.jsx
src/components/Upload/__demo__/uncontrolled.jsx
src/components/Upload/__demo__/upload.jsx
src/components/Upload/__tests__/__snapshots__/demo.test.js.snap

feat(Upload): support single select

---

src/components/Select/Select.jsx
src/components/Select/Select.md
src/components/Select/__demo__/customStyle.jsx
src/components/Select/__demo__/extra.jsx
src/components/Select/__tests__/__snapshots__/demo.test.js.snap
src/components/Select/style/index.js

feat(Select): add custom style

---

src/components/LocaleProvider/__tests__/__snapshots__/demo.test.js.snap
src/components/LocaleProvider/__tests__/__snapshots__/index.test.js.snap
src/components/Table/Table.jsx
src/components/Table/__tests__/__snapshots__/demo.test.js.snap
src/components/Table/style/index.js
src/libs/rc-table/Table.js

feat(Table): add scroll.onScroll and fix fixed column style

---

src/components/Calendar/Calendar.jsx
src/components/Calendar/style/index.js

fix(Calendar): fix calendar wrong ref

---

src/components/LocaleProvider/__tests__/__snapshots__/index.test.js.snap
src/components/Slider/__tests__/__snapshots__/index.test.js.snap
src/components/Tooltip/__tests__/__snapshots__/demo.test.js.snap
src/components/Tooltip/__tests__/__snapshots__/index.test.js.snap
src/components/Tooltip/style/index.js

feat(Tooltip): change tooltip arrow position

---

src/components/LocaleProvider/__demo__/list.jsx
src/components/LocaleProvider/__tests__/__snapshots__/demo.test.js.snap
src/components/LocaleProvider/__tests__/__snapshots__/index.test.js.snap
src/components/LocaleProvider/__tests__/index.test.js
src/components/Table/Table.jsx
src/components/Table/__tests__/__snapshots__/demo.test.js.snap
src/components/Table/locale/en_US.js
src/components/Table/locale/zh_CN.js
src/components/Table/style/index.js

feat(Table): add select tooltip for table select

---

.styleguide/components/ReactExample.jsx
src/components/Checkbox/__tests__/__snapshots__/demo.test.js.snap
src/components/Checkbox/style/index.js
src/components/Collapse/__tests__/__snapshots__/demo.test.js.snap
src/components/LocaleProvider/__tests__/__snapshots__/demo.test.js.snap
src/components/LocaleProvider/__tests__/__snapshots__/index.test.js.snap
src/components/Menu/__tests__/__snapshots__/demo.test.js.snap
src/components/Select/Select.jsx
src/components/Select/Select.md
src/components/Select/__demo__/emptyContent.jsx
src/components/Select/__tests__/__snapshots__/demo.test.js.snap
src/components/Select/locale/en_US.js
src/components/Select/locale/zh_CN.js
src/components/Select/style/index.js
src/components/Table/__tests__/__snapshots__/demo.test.js.snap

feat(Select): add empty content for none option display

---

.styleguide/components.json
src/components/Combine/Combine.jsx
src/components/Combine/Combine.md
src/components/Combine/__demo__/combine.jsx
src/components/Combine/__demo__/demo.jsx
src/components/Combine/__demo__/sharedProps.jsx
src/components/Combine/__demo__/spacing.jsx
src/components/Combine/__tests__/__snapshots__/demo.test.js.snap
src/components/Combine/__tests__/demo.test.js
src/components/Combine/index.jsx
src/components/Combine/style/index.js
src/components/Compact/Compact.jsx
src/components/Compact/__tests__/__snapshots__/demo.test.js.snap
src/components/Compact/style/index.js

feat(Combine): add Combine and change compact to combine

---

src/components/LocaleProvider/__tests__/__snapshots__/index.test.js.snap
src/components/Slider/__tests__/__snapshots__/index.test.js.snap
src/components/Tooltip/Tooltip.jsx
src/components/Tooltip/__tests__/__snapshots__/index.test.js.snap
src/components/Tooltip/style/index.js

feat(Tooltip): add customStyle & change offset

---

.styleguide/components.json
src/components/LocaleProvider/__demo__/list.jsx
src/components/LocaleProvider/__tests__/__snapshots__/demo.test.js.snap
src/components/LocaleProvider/__tests__/__snapshots__/index.test.js.snap
src/components/LocaleProvider/locale/en_US.js
src/components/LocaleProvider/locale/zh_CN.js
src/components/PopConfirm/PopConfirm.jsx
src/components/PopConfirm/PopConfirm.md
src/components/PopConfirm/__demo__/demo.jsx
src/components/PopConfirm/__demo__/onCancel.jsx
src/components/PopConfirm/__demo__/onConfirm.jsx
src/components/PopConfirm/__demo__/popConfirm.jsx
src/components/PopConfirm/__tests__/__snapshots__/demo.test.js.snap
src/components/PopConfirm/__tests__/demo.test.js
src/components/PopConfirm/index.jsx
src/components/PopConfirm/locale/en_US.js
src/components/PopConfirm/locale/zh_CN.js
src/components/PopConfirm/style/index.js

feat(PopConfirm): add popconfirm component

---

src/components/LocaleProvider/__tests__/__snapshots__/demo.test.js.snap
src/components/LocaleProvider/__tests__/__snapshots__/index.test.js.snap
src/components/NumberInput/NumberInput.jsx
src/components/NumberInput/NumberInput.md
src/components/NumberInput/__demo__/tooltip.jsx
src/components/NumberInput/__tests__/__snapshots__/demo.test.js.snap
src/components/Slider/__tests__/__snapshots__/index.test.js.snap
src/components/Table/__tests__/__snapshots__/demo.test.js.snap
src/components/Tooltip/Tooltip.md
src/components/Tooltip/__demo__/style.jsx
src/components/Tooltip/__tests__/__snapshots__/demo.test.js.snap
src/components/Tooltip/__tests__/__snapshots__/index.test.js.snap
src/components/Tooltip/style/index.js

feat(NumberInput): add tooltip for numberinput tip display

---

src/components/LocaleProvider/__tests__/__snapshots__/demo.test.js.snap
src/components/LocaleProvider/__tests__/__snapshots__/index.test.js.snap
src/components/Slider/__tests__/__snapshots__/index.test.js.snap
src/components/Table/Table.jsx
src/components/Table/__demo__/table.jsx
src/components/Table/__tests__/__snapshots__/demo.test.js.snap
src/components/Tooltip/__tests__/__snapshots__/demo.test.js.snap
src/components/Tooltip/__tests__/__snapshots__/index.test.js.snap
src/components/Tooltip/style/index.js

feat(Table): add rowSelction.selectedTip

---

src/components/Table/Table.jsx
src/components/Table/__tests__/__snapshots__/demo.test.js.snap

feat(Table): set tableLayout to fixed when scroll true

---

src/components/EditableTable/__tests__/__snapshots__/demo.test.js.snap
src/components/LocaleProvider/__tests__/__snapshots__/demo.test.js.snap
src/components/LocaleProvider/__tests__/__snapshots__/index.test.js.snap
src/components/Table/Table.md
src/components/Table/__demo__/fixed.jsx
src/components/Table/__demo__/scroll.jsx
src/components/Table/__tests__/__snapshots__/demo.test.js.snap
src/components/Table/style/index.js
src/components/TransferTable/__tests__/__snapshots__/demo.test.js.snap

fix(Table): remove overflow-x auto

---

.styleguide/components/StyleGuideRenderer.jsx
src/components/Card/Card.jsx
src/components/Card/Card.md
src/components/Card/__demo__/popupContainer.jsx
src/components/Card/__tests__/__snapshots__/demo.test.js.snap
src/components/Card/style/index.js
src/components/DatePicker/DatePicker.jsx
src/components/DatePicker/Month.jsx
src/components/DatePicker/Range.jsx
src/components/Drawer/Drawer.jsx
src/components/Drawer/Drawer.md
src/components/Drawer/__demo__/popupContainer.jsx
src/components/LocaleProvider/__tests__/__snapshots__/index.test.js.snap
src/components/Modal/Modal.jsx
src/components/Modal/Modal.md
src/components/Modal/__demo__/popupContainer.jsx
src/components/Modal/__tests__/__snapshots__/demo.test.js.snap
src/components/Pagination/Options.jsx
src/components/Popover/ContainerContext.jsx
src/components/Popover/Popover.jsx
src/components/Popover/Popover.md
src/components/Popover/__demo__/forwardPopupContainer.jsx
src/components/Popover/__tests__/__snapshots__/demo.test.js.snap
src/components/Select/Select.jsx
src/components/Select/Select.md
src/components/Table/ActionList.jsx
src/components/Table/Table.jsx
src/components/Table/Table.md
src/components/Table/__demo__/popupContainer.jsx
src/components/Table/__tests__/__snapshots__/demo.test.js.snap

feat(PopupContainer): add popupContainer to most components

---

.gitignore
src/components/Button/__tests__/index.test.js
src/components/Radio/__tests__/index.test.js

Add test scope desc for Radio and Button Component
*   [x] Follow our contributing docs
*   [x] Docs have been added/updated
*   [x] Tests have been added; existing tests pass

test(test): add test for Radio and Button

---

src/components/Breadcrumb/Item.jsx
src/components/Breadcrumb/__tests__/index.test.js
src/components/Menu/__tests__/index.test.js

test update
*   [x] Follow our contributing docs
*   [x] Tests have been added; existing tests pass

test(Menu): add tests for Breadcrumb and Menu

---

.eslintignore
index.d.ts
package.json
src/components/Drawer/Drawer.jsx
src/components/Message/method.jsx
src/components/Modal/method.jsx
src/components/ZForm/controllerDecorator.jsx
yarn.lock

*   [x] Tests have been added; existing tests pass

feat(Interface): update index.d.ts

---

.styleguide/components.json
src/components/ActionList/ActionList.jsx
src/components/ActionList/ActionList.md
src/components/ActionList/__demo__/actionChildren.jsx
src/components/ActionList/__demo__/actionList.jsx
src/components/ActionList/__demo__/dropdownButton.jsx
src/components/ActionList/__demo__/exposeCount.jsx
src/components/ActionList/__demo__/popoverProps.jsx
src/components/ActionList/__demo__/size.jsx
src/components/ActionList/__demo__/smart.jsx
src/components/ActionList/__demo__/tooltip.jsx
src/components/ActionList/__tests__/__snapshots__/demo.test.js.snap
src/components/ActionList/__tests__/demo.test.js
src/components/ActionList/index.jsx
src/components/ActionList/style/index.js

feat(ActionList): move outside & add dropdownButton & tooptip

---

index.d.ts

*   [x] Docs have been added/updated

docs(Interface): ObjectExclude add Partial

---

index.d.ts

fix(index.d.ts): inputStyle capitalization error

---

index.d.ts

fix(Interface): fix children component type error in index.d.ts

---

src/components/Tag/Icon.jsx
src/components/Tag/Icon.md
src/components/Tag/Tag.jsx
src/components/Tag/Tag.md
src/components/Tag/__demo__/icon-customStyle.jsx
src/components/Tag/__demo__/tag-customStyle.jsx
src/components/Tag/__tests__/__snapshots__/demo.test.js.snap
src/components/Tag/style/index.js

feat(Tag): add support of customStyle

---

src/libs/rc-table/Table.js

fix(Table): fix sticky style when resize

---

index.d.ts

fix(Interface): table pagination can be null

---

src/components/Checkbox/__tests__/__snapshots__/demo.test.js.snap
src/components/ConfigProvider/__tests__/__snapshots__/demo.test.js.snap
src/components/EditableTable/__tests__/__snapshots__/demo.test.js.snap
src/components/Form/style/index.tsx
src/components/LocaleProvider/__tests__/__snapshots__/demo.test.js.snap
src/components/LocaleProvider/__tests__/__snapshots__/index.test.js.snap
src/components/Radio/__tests__/__snapshots__/demo.test.js.snap
src/components/Radio/style/index.js
src/components/Switch/style/index.ts
src/components/Table/__tests__/__snapshots__/demo.test.js.snap
src/components/Table/style/index.js
src/components/ThemeProvider/designTokens.ts
src/components/ThemeProvider/designTokensDark.ts
src/components/TransferTable/__tests__/__snapshots__/demo.test.js.snap

add design tokens to switch, table and form

feat: add design tokens

---

src/components/Table/Table.jsx
src/components/Table/__demo__/cellMerge.jsx
src/components/Table/__tests__/__snapshots__/demo.test.js.snap
src/components/Table/__tests__/index.test.js
src/libs/rc-table/ExpandableRow.js
src/libs/rc-table/ExpandableTable.js
src/libs/rc-table/Table.js
src/libs/rc-table/TableCell.js

fix(table): add fault-tolerant when record is undefined

---

src/components/Select/Select.tsx

feat(select): renderContent support new search style

---

src/components/Modal/Modal.jsx

fix(modal): the close button is missing a key

---

.recodo/index.tsx

feat(theme): component theme switch

---

.recodo/data/Nav.info.json
index.d.ts
src/components/Nav/Nav.tsx
src/components/Nav/NavContext.tsx
src/components/Nav/NavItem.tsx
src/components/Nav/__tests__/__snapshots__/demo.test.js.snap
src/components/Nav/__tests__/index.test.js
src/components/Nav/style/index.js

fix(nav): fix selectedKeys bug when switch inlineCollapsed

---

src/components/Textarea/__tests__/__snapshots__/demo.test.js.snap
src/components/Textarea/style/index.js

fix(textarea): fix font color

---

src/components/Table/Table.jsx
src/components/Table/__demo__/columnConfigButton-modalProps.jsx
src/components/Table/__demo__/columnConfigButton.jsx
src/components/Table/__tests__/index.test.js
src/components/Table/utils.js

1.修复在不同浏览器下对localStorage方法的错误判断
2.column在filter重置成其他状态时判断的补全

fix(table): verify localStorage 

---

src/components/DatePicker/Range.tsx
src/components/DatePicker/__tests__/index.test.js

When the Range is in an error status, if the input is clicked to set a new value, that will cause the onChange function returns an unexpected null value

fix onChange returns an unexpected null value

---

src/components/Tabs/TabBar.tsx
src/components/Tabs/Tabs.tsx
src/components/Tabs/__demo__/tabs.jsx
src/components/Tabs/__tests__/__snapshots__/demo.test.js.snap
src/components/Tabs/style/index.ts

feat(tabs): add additional slots to the tab

feat(tabs): add additional slots to the tab

---

src/components/Table/Table.jsx
src/components/Table/__tests__/index.test.js
src/components/Table/style/index.js

fix(table): tabel filter disabled

---

src/components/Message/method.jsx

增加兜底逻辑，container渲染ref为null阻止调用

fix(message): messagecontainer ref is null

---

src/components/AutoComplete/AutoComplete.tsx
src/components/AutoComplete/__demo__/autoComplete.jsx
src/components/AutoComplete/__tests__/__snapshots__/demo.test.js.snap

fix(AutoComplete): add size

---

src/components/Table/Table.jsx
src/components/Table/__tests__/__snapshots__/demo.test.js.snap
src/components/Table/__tests__/index.test.js

fix(table): remove drag classname

---

src/components/ConfigProvider/__tests__/__snapshots__/demo.test.js.snap
src/components/EditableTable/__tests__/__snapshots__/demo.test.js.snap
src/components/LocaleProvider/__tests__/__snapshots__/demo.test.js.snap
src/components/LocaleProvider/__tests__/__snapshots__/index.test.js.snap
src/components/Table/__tests__/__snapshots__/demo.test.js.snap
src/components/Table/style/index.js
src/components/TransferTable/__tests__/__snapshots__/demo.test.js.snap

feat(table): change pagination margintop

---

src/components/Steps/Step.jsx
src/components/Steps/StepIcon.jsx
src/components/Steps/Steps.jsx
src/components/Steps/Steps.md
src/components/Steps/__demo__/steps-change.jsx
src/components/Steps/__demo__/steps-vertical.jsx
src/components/Steps/__demo__/steps.jsx
src/components/Steps/__tests__/__snapshots__/demo.test.js.snap
src/components/Steps/style/index.js

feat(steps): steps new version

---

src/components/Steps/Step.jsx
src/components/Steps/Steps.jsx
src/components/Steps/__demo__/steps-steps.jsx
src/components/Steps/__demo__/steps.jsx
src/components/Steps/__tests__/__snapshots__/demo.test.js.snap
src/components/Steps/style/index.js

feat(Steps): add nowrap props

---

.recodo/componentDemos/Steps.tsx
index.d.ts
src/components/Steps/Step.jsx
src/components/Steps/__demo__/steps.jsx
src/components/Steps/__tests__/__snapshots__/demo.test.js.snap
src/components/Steps/style/index.js

feat(Steps): hidden remark

---

src/components/Message/style/index.js

feat(Message): add h3 bold

---

src/components/Steps/__tests__/__snapshots__/demo.test.js.snap
src/components/Steps/style/index.js

fix(Steps):width style

---

.recodo/data/Cascader.info.json
src/components/Cascader/Cascader.tsx
src/components/Cascader/__demo__/cascader.jsx
src/components/Cascader/__tests__/__snapshots__/demo.test.js.snap
src/components/Form/__tests__/__snapshots__/demo.test.js.snap
src/components/Form/style/index.tsx
src/components/ZForm/__tests__/__snapshots__/demo.test.js.snap

feat(Cascader): add separator

---

src/components/AutoComplete/AutoComplete.tsx

feat(autocomplete): add input props

---

src/components/Select/Select.tsx
src/components/Select/__demo__/select.jsx
src/components/Select/__tests__/__snapshots__/demo.test.js.snap
src/components/Select/style/index.tsx
src/hooks/useOverflow.tsx

feat(Select): add error status

---

src/components/Table/Table.jsx
src/components/Table/Table.md
src/components/Table/__demo__/subTableForCheckBox.jsx
src/components/Table/__tests__/__snapshots__/demo.test.js.snap
src/components/Table/__tests__/index.test.js

feat(Table): rowSelection增加聚合

---

index.d.ts

*   [x] Follow our contributing docs
*   [x] Docs have been added/updated
*   [x] Tests have been added; existing tests pass

docs(Interface): update index.d.ts

---

src/components/DatePicker/DatePicker.tsx
src/components/DatePicker/Month.tsx
src/components/DatePicker/Range.tsx
src/components/DatePicker/usePicker.tsx

fix(DatePicker): adjustX

---

src/components/ZForm/__demo__/rule.jsx
src/components/ZForm/__tests__/__snapshots__/demo.test.js.snap
src/components/ZForm/__tests__/index.test.js
src/components/ZForm/controllerDecorator.jsx

fix(ZForm): fix validator null

---

src/components/LocaleProvider/__tests__/__snapshots__/demo.test.js.snap
src/components/LocaleProvider/__tests__/__snapshots__/index.test.js.snap
src/components/Menu/locale/en_US.js
src/components/Modal/locale/en_US.js
src/components/Pagination/locale/en_US.js
src/components/PopConfirm/locale/en_US.js
src/components/Select/locale/en_US.js
src/components/Slider/locale/en_US.js
src/components/Table/locale/en_US.js

feat(locale): update locale of en

---

src/components/Table/Table.jsx
src/components/Table/Table.md
src/components/Table/__demo__/loadingDataFromRemoteForrowSelection.jsx
src/components/Table/__tests__/__snapshots__/demo.test.js.snap

远程请求场景 datasource发生变化支持清除rowSelection中的selectedRowKeys

feat(Table): table add reset selected

---

src/components/Tabs/TabBar.tsx

fix(TabBar): flex type

---

src/components/Select/Select.tsx
src/components/Select/__demo__/renderContent.jsx
src/components/Select/__tests__/__snapshots__/demo.test.js.snap

fix(Select): multiple add renderContent
